name: Update on new image

on:
  schedule:
    - cron: '*/5 * * * *'

permissions:
  contents: write

jobs:
  info:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: |
        DIGEST=$(docker manifest inspect ghcr.io/2xb/kassiopeia/full:main | jq -r .config.digest)
    
        echo "FROM ghcr.io/${REPO}:${DIGEST}" > Dockerfile

        if [[ `git status --porcelain` ]]; then
          git add .
          git config user.name "GitHub CI"
          git config user.email "<>"
          git commit -m "Automatic update by GitHub CI"
          git push origin main
        fi

